#configure server
server:
  port: 8091


#configure spring datasource,jpa, mail and servlet
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inscription_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: lenguesandra@gmail.com
    password: ohqh nkcm ebpe lplz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB



#configure application
application:
  upload:
    allowed-file-types:
      - application/pdf
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - image/jpeg
      - image/png
    allowed-extensions: [ pdf, docx, jpg, jpeg, png ]
  security:
    jwt:
      secret-key: C003FA3DC88493379ABFCC2779594D1MYSECRETKEY1233ADMIN
      expiration: 900000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

#configure springdoc (swagger)
springdoc:
  default-produces-media-type: application/json
#  swagger-ui:
#    try-it-out-enabled: true
#    persist-authorization: true
#    filter: true
#    request-snippets-enabled: true
#    syntax-highlight:
#      activate: true
#      theme: "agate"


